// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("postgresql://f52197ff0c348f2b821cce6ec88d384444bd7985f0b508a3fd15fd392f50c847:sk_poKi7h4QrHMGjcs9OIoGl@db.prisma.io:5432/postgres?sslmode=require"),
  },
});
